module.exports = {
    name: "reto",
    desc: "Sirve para obtener un reto",
    premium: false,
    run: async (client, message, args, prefix) => {
       const array = [" Abraza a la persona que NO te agrada en clase y di: 'Muchas gracias por ser la mejor persona para mí' ", " Ve a un campo amplio, luego corre lo más rápido posible mientras dices 'Estoy loco, estoy loco' ", " Elige a una persona al azar en la calle, luego di 'No sabes cuan hermosa eres'", " Nombra de 1 azul a 20 azules rápidamente y no debes cometer ningún error. Si está mal, debe repetirse desde el principio.", " Póngase una corona de papel de copia y diga a todos en la habitación 'HONOR AL REY' mientras señala a cada persona con una regla.", " Abraza a la persona que NO te agrada en clase y di: 'Muchas gracias por ser la mejor persona para mí' ", " Beba algo que haya sido preparado / acordado, pero asegúrese de que no sea peligroso, puede ser como beber jarabe mezclado con salsa de soja.", " Habla con el emoticono-miedo de la persona que te gusta", " Canta tu película de Disney favorita fuera de casa mientras gritas.", " Pídale dinero a alguien (al azar ) en la calle diciendo 'No tengo dinero para tomar una cerveza'.", "Lee en alto el último mensaje que has recibido.", "No digas ‘si’ o ’no’ durante 1 minuto.", "Di la tabla de multiplicar del 2.", "Demuestra un talento oculto que tengas.", "Llamar a un número desconocido y pedir una pizza. Insistir aunque la persona diga que no es una pizzería.", "Salir al balcón y grabarse gritando ¡chupitos gratis en mi casa!", "Subir a Facebook una de tus peores selfies", "Publicar un estado de WhatsApp vergonzoso", "Mandar una captura de pantalla a tus amigos en la que se vea que le confiesas tu amor a una persona de su elección", "Poner la foto de perfil de uno de tus amigos durante 1 día", "omparte con el resto del grupo un vídeo subido de tono que te guste.", "Haz una lista con las partes del cuerpo que más te gustan de otra persona del grupo.", "Manda un mensaje solo con emojis, otra persona de tu elección tendrá que decodificarlos.", "Hazte una foto haciendo la peineta y mándasela a quien digan tus amigos.", "Imita el grito de cinco animales", "Imita el acento marsellés", "Dibuja un cordero", "Canta tu canción preferida", "Da la vuelta a la sala como un pato", "Envía un mensaje de texto al primer número de tu agenda", "Haz un striptease", "Envia un video bailando el Gangnam Style", "Canta una canción de mon laferte"] //hacemos un array con todas las posibles respuestas

        message.reply(`Reto:\n\`\`\`${array[(Math.floor(Math.random() * array.length))]}\`\`\``) //Aquí enviamos un mensaje con la posible respuesta dentro del array 
    }
}
